# Generated by Django 5.1.1 on 2026-02-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_designcategory_design'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='design',
            options={'verbose_name_plural': 'Designs'},
        ),
        migrations.AlterModelOptions(
            name='designcategory',
            options={'verbose_name': 'Design Category', 'verbose_name_plural': 'Design Categories'},
        ),
        migrations.AlterField(
            model_name='design',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='design'),
        ),
    ]
